/** Instantly API v2 allowed schedule timezones (subset of IANA). */
export const INSTANTLY_TIMEZONES = [
  "Etc/GMT+12",
  "Etc/GMT+11",
  "Etc/GMT+10",
  "America/Anchorage",
  "America/Dawson",
  "America/Creston",
  "America/Chihuahua",
  "America/Boise",
  "America/Belize",
  "America/Chicago",
  "America/Bahia_Banderas",
  "America/Regina",
  "America/Bogota",
  "America/Detroit",
  "America/Indiana/Marengo",
  "America/Caracas",
  "America/Asuncion",
  "America/Glace_Bay",
  "America/Campo_Grande",
  "America/Anguilla",
  "America/Santiago",
  "America/St_Johns",
  "America/Sao_Paulo",
  "America/Argentina/La_Rioja",
  "America/Araguaina",
  "America/Godthab",
  "America/Montevideo",
  "America/Bahia",
  "America/Noronha",
  "America/Scoresbysund",
  "Atlantic/Cape_Verde",
  "Africa/Casablanca",
  "America/Danmarkshavn",
  "Europe/Isle_of_Man",
  "Atlantic/Canary",
  "Africa/Abidjan",
  "Arctic/Longyearbyen",
  "Europe/Belgrade",
  "Africa/Ceuta",
  "Europe/Sarajevo",
  "Africa/Algiers",
  "Africa/Windhoek",
  "Asia/Nicosia",
  "Asia/Beirut",
  "Africa/Cairo",
  "Asia/Damascus",
  "Europe/Bucharest",
  "Africa/Blantyre",
  "Europe/Helsinki",
  "Europe/Istanbul",
  "Asia/Jerusalem",
  "Africa/Tripoli",
  "Asia/Amman",
  "Asia/Baghdad",
  "Europe/Kaliningrad",
  "Asia/Aden",
  "Africa/Addis_Ababa",
  "Europe/Kirov",
  "Europe/Astrakhan",
  "Asia/Tehran",
  "Asia/Dubai",
  "Asia/Baku",
  "Indian/Mahe",
  "Asia/Tbilisi",
  "Asia/Yerevan",
  "Asia/Kabul",
  "Antarctica/Mawson",
  "Asia/Yekaterinburg",
  "Asia/Karachi",
  "Asia/Kolkata",
  "Asia/Colombo",
  "Asia/Kathmandu",
  "Antarctica/Vostok",
  "Asia/Dhaka",
  "Asia/Rangoon",
  "Antarctica/Davis",
  "Asia/Novokuznetsk",
  "Asia/Hong_Kong",
  "Asia/Krasnoyarsk",
  "Asia/Brunei",
  "Australia/Perth",
  "Asia/Taipei",
  "Asia/Choibalsan",
  "Asia/Irkutsk",
  "Asia/Dili",
  "Asia/Pyongyang",
  "Australia/Adelaide",
  "Australia/Darwin",
  "Australia/Brisbane",
  "Australia/Melbourne",
  "Antarctica/DumontDUrville",
  "Australia/Currie",
  "Asia/Chita",
  "Antarctica/Macquarie",
  "Asia/Sakhalin",
  "Pacific/Auckland",
  "Etc/GMT-12",
  "Pacific/Fiji",
  "Asia/Anadyr",
  "Asia/Kamchatka",
  "Etc/GMT-13",
  "Pacific/Apia",
] as const;

const ALLOWED = new Set<string>(INSTANTLY_TIMEZONES);

/** Default for new campaigns (US Eastern — on Instantly's allow list). */
export const DEFAULT_INSTANTLY_TIMEZONE = "America/Detroit";

const ALIASES: Record<string, string> = {
  "Etc/UTC": "Africa/Abidjan",
  UTC: "Africa/Abidjan",
  "America/New_York": "America/Detroit",
  "US/Eastern": "America/Detroit",
  "America/Los_Angeles": "America/Boise",
  "US/Pacific": "America/Boise",
  "America/Denver": "America/Boise",
  "US/Mountain": "America/Boise",
  "America/Phoenix": "America/Creston",
  "Europe/London": "Europe/Isle_of_Man",
  "Europe/Paris": "Europe/Belgrade",
  "Europe/Berlin": "Europe/Belgrade",
  "Asia/Singapore": "Asia/Hong_Kong",
};

/** Map common IANA zones to Instantly v2 schedule timezone enum values. */
export function normalizeInstantlyTimezone(timezone?: string | null): string {
  const tz = timezone?.trim();
  if (!tz) return DEFAULT_INSTANTLY_TIMEZONE;
  if (ALLOWED.has(tz)) return tz;
  const mapped = ALIASES[tz];
  if (mapped && ALLOWED.has(mapped)) return mapped;
  return DEFAULT_INSTANTLY_TIMEZONE;
}
