import type {
  IntentOpportunityRoute,
  IntentPlaybook,
  IntentQualificationRules,
  IntentSignalDefinition,
} from "@/lib/intent/types";

const RESEARCH = [
  "triggerEvent",
  "painPoints",
  "businessFocus",
  "hiringSignals",
  "recentNews",
  "psLine",
  "toolsUsed",
  "notes",
  "contactTitle",
] as const;

function demand(
  partial: Omit<IntentSignalDefinition, "enabled" | "qualificationRole"> & {
    enabled?: boolean;
  },
): IntentSignalDefinition {
  return {
    enabled: true,
    qualificationRole: "demand",
    fieldKeys: [...RESEARCH],
    ...partial,
  };
}

function supporting(
  partial: Omit<IntentSignalDefinition, "enabled" | "qualificationRole"> & {
    enabled?: boolean;
  },
): IntentSignalDefinition {
  return {
    enabled: true,
    qualificationRole: "supporting",
    fieldKeys: [...RESEARCH],
    ...partial,
  };
}

export const STELLIX_QUALIFICATION: IntentQualificationRules = {
  requireDemandSignal: true,
  minCategories: 2,
  partnerSearchSignalIds: ["stellix_partner_search"],
  maxHiringPoints: 10,
  maxWebsitePoints: 10,
  maxOperationalPainPoints: 30,
  maxSupportingBundlePoints: 15,
  supportingBundleSignalIds: [
    "stellix_funding",
    "stellix_expansion",
    "stellix_leadership",
    "stellix_legacy_ms_stack",
    "stellix_hiring",
  ],
};

export const STELLIX_OPPORTUNITY_ROUTES: IntentOpportunityRoute[] = [
  {
    id: "legacy_modernization",
    label: "Legacy Modernization",
    signalIds: ["stellix_legacy_initiative", "stellix_legacy_ms_stack", "stellix_tech_debt"],
  },
  {
    id: "iot_rfid",
    label: "IoT and RFID",
    signalIds: ["stellix_iot", "stellix_rfid"],
  },
  {
    id: "logistics_software",
    label: "Logistics Software",
    signalIds: ["stellix_logistics", "stellix_visibility_pain"],
  },
  {
    id: "enterprise_apps",
    label: "Enterprise Applications",
    signalIds: ["stellix_enterprise_software", "stellix_erp_crm_portal", "stellix_saas"],
  },
  {
    id: "integrations_automation",
    label: "Integrations and Automation",
    signalIds: ["stellix_integrations", "stellix_workflow_automation", "stellix_manual_pain"],
  },
  {
    id: "cloud_devops",
    label: "Cloud and DevOps",
    signalIds: ["stellix_cloud_migration", "stellix_devops", "stellix_scalability_pain"],
  },
  {
    id: "ai_solutions",
    label: "AI Solutions",
    signalIds: ["stellix_ai"],
  },
  {
    id: "dedicated_team",
    label: "Dedicated Team",
    signalIds: ["stellix_dedicated_team", "stellix_hiring"],
  },
  {
    id: "salesforce",
    label: "Salesforce",
    signalIds: ["stellix_salesforce"],
  },
  {
    id: "healthcare_software",
    label: "Healthcare Software",
    signalIds: ["stellix_healthcare", "stellix_compliance"],
  },
  {
    id: "mobile_apps",
    label: "Mobile Applications",
    signalIds: ["stellix_mobile"],
  },
  {
    id: "web_platform",
    label: "Web Platform",
    signalIds: ["stellix_website"],
  },
];

/** Master Stellix Soft Qualified Opportunities playbook (28 signals). */
export function stellixSoftPlaybook(): IntentPlaybook {
  return {
    templateId: "stellix_soft",
    name: "Stellix Soft Qualified Opportunities",
    outreachThreshold: 45,
    tempBands: { warmMin: 45, hotMin: 70 },
    autoTemperature: true,
    scoringMode: "absolute",
    engagement: { reply: 10, multiTouch: 2, multiTouchMin: 3 },
    qualification: STELLIX_QUALIFICATION,
    opportunityRoutes: STELLIX_OPPORTUNITY_ROUTES,
    signals: [
      demand({
        id: "stellix_partner_search",
        label: "Searching for a Software Partner",
        category: "custom",
        points: 35,
        keywords: [
          "software development rfp",
          "application development rfp",
          "seeking software development partner",
          "seeking technology partner",
          "software vendor selection",
          "outsourced software development partner",
          "request for proposal software development",
          "application modernization rfp",
          "seeking software implementation partner",
        ],
      }),
      demand({
        id: "stellix_enterprise_software",
        label: "Custom Enterprise Software Project",
        category: "digital_transformation",
        points: 25,
        keywords: [
          "custom enterprise software",
          "enterprise application development",
          "custom operations platform",
          "mission-critical software platform",
          "internal business application",
          "enterprise software initiative",
          "new business platform",
          "custom software transformation",
          "automotive intelligence platform",
          "intelligence platform for",
          "enterprise software contract",
          "long-term software contract",
          "cloud-based operations platform",
        ],
      }),
      demand({
        id: "stellix_dedicated_team",
        label: "Dedicated Development Team Requirement",
        category: "custom",
        points: 30,
        keywords: [
          "dedicated development team",
          "outsourced engineering team",
          "staff augmentation partner",
          "augment software engineering team",
          "managed development team",
          "external engineering capacity",
          "nearshore development partner",
          "remote software development team",
          "development capacity partner",
        ],
      }),
      demand({
        id: "stellix_legacy_initiative",
        label: "Legacy Modernization Initiative",
        category: "legacy_stack",
        points: 28,
        keywords: [
          "legacy application modernization",
          "legacy system modernization",
          "application modernization program",
          "legacy migration project",
          "software replatforming",
          "monolith modernization",
          "modernize existing application",
          "legacy platform replacement",
          "application rearchitecture",
          "legacy dealer management",
          "legacy dms",
          "replace legacy dms",
          "modernize dealer systems",
          "aging dealer systems",
        ],
      }),
      supporting({
        id: "stellix_legacy_ms_stack",
        label: "Legacy Microsoft Stack Detected",
        category: "legacy_stack",
        points: 15,
        keywords: [
          "vb.net",
          "visual basic .net",
          "asp.net web forms",
          "asp.net webforms",
          ".net framework",
          "windows forms",
          "winforms",
          "wcf services",
          "asmx web services",
          "silverlight",
          "visual basic application",
        ],
        fieldKeys: ["toolsUsed", "triggerEvent", "painPoints", "businessFocus", "notes", "hiringSignals"],
      }),
      demand({
        id: "stellix_tech_debt",
        label: "Technical Debt or Legacy Maintenance Pain",
        category: "operational_pain",
        points: 18,
        keywords: [
          "technical debt",
          "unsupported legacy application",
          "aging software platform",
          "difficult to maintain system",
          "legacy maintenance burden",
          "obsolete application",
          "end of support software",
          "legacy developer shortage",
          "high software maintenance cost",
          "fragile legacy system",
          "disjointed tech stacks",
          "disjointed tech stack",
          "inefficiencies and lost margins",
          "lost margins in",
        ],
      }),
      demand({
        id: "stellix_iot",
        label: "IoT or Connected Device Platform",
        category: "technology",
        points: 25,
        keywords: [
          "iot platform development",
          "connected device platform",
          "device management portal",
          "remote device monitoring",
          "device provisioning platform",
          "mqtt platform",
          "telemetry platform",
          "firmware update management",
          "connected hardware software",
          "device fleet management",
        ],
        industries: [
          "iot",
          "hardware",
          "electronics",
          "manufacturing",
          "industrial automation",
          "healthcare",
          "medtech",
          "logistics",
        ],
      }),
      demand({
        id: "stellix_rfid",
        label: "RFID or Asset-Tracking Initiative",
        category: "supply_chain",
        points: 28,
        keywords: [
          "rfid implementation",
          "rfid asset tracking",
          "rfid inventory tracking",
          "rfid reader integration",
          "real-time asset tracking",
          "item-level tracking",
          "rfid deployment",
          "barcode to rfid migration",
          "rfid warehouse system",
          "fixed rfid readers",
        ],
        industries: [
          "logistics",
          "warehousing",
          "supply chain",
          "manufacturing",
          "distribution",
          "retail",
          "healthcare",
          "hardware",
        ],
      }),
      demand({
        id: "stellix_logistics",
        label: "Logistics or Warehouse Digitization",
        category: "supply_chain",
        points: 24,
        keywords: [
          "warehouse digitization",
          "logistics software platform",
          "dispatch management system",
          "shipment tracking platform",
          "fleet management platform",
          "driver application",
          "inventory visibility initiative",
          "warehouse management integration",
          "transportation management platform",
          "route optimization system",
        ],
        industries: [
          "logistics",
          "transportation",
          "warehousing",
          "supply chain",
          "distribution",
          "manufacturing",
          "retail",
        ],
      }),
      demand({
        id: "stellix_erp_crm_portal",
        label: "ERP, CRM or Enterprise Portal Project",
        category: "digital_transformation",
        points: 24,
        keywords: [
          "custom erp development",
          "custom crm development",
          "customer portal development",
          "partner portal development",
          "employee portal development",
          "replace legacy erp",
          "replace legacy crm",
          "self-service portal",
          "vendor portal development",
          "operations management portal",
        ],
      }),
      demand({
        id: "stellix_integrations",
        label: "Systems and API Integration Project",
        category: "technology",
        points: 20,
        keywords: [
          "erp integration project",
          "crm integration project",
          "api integration project",
          "systems integration initiative",
          "data synchronization project",
          "legacy system integration",
          "sap integration",
          "oracle integration",
          "netsuite integration",
          "dynamics 365 integration",
          "third-party api integration",
          "integrating accounting, sales, crm",
          "integrating accounting sales crm",
          "unify accounting, sales, crm",
          "cross-system workflows",
          "cross system workflows",
        ],
      }),
      demand({
        id: "stellix_saas",
        label: "SaaS or Multi-Tenant Platform",
        category: "digital_transformation",
        points: 22,
        keywords: [
          "multi-tenant saas platform",
          "build saas product",
          "saas platform modernization",
          "scale saas architecture",
          "white-label software platform",
          "subscription platform development",
          "b2b saas development",
          "tenant isolation architecture",
          "saas product expansion",
        ],
        industries: [
          "enterprise software",
          "saas",
          "fintech",
          "healthcare",
          "medtech",
          "logistics",
          "technology",
        ],
      }),
      demand({
        id: "stellix_mobile",
        label: "Mobile or Field Application",
        category: "custom",
        points: 18,
        keywords: [
          "enterprise mobile application",
          "field service mobile app",
          "driver mobile app",
          "customer mobile application",
          "workforce mobile app",
          "flutter application development",
          "react native application",
          "mobile app modernization",
          "mobile operations platform",
          "technician mobile app",
        ],
      }),
      demand({
        id: "stellix_workflow_automation",
        label: "Workflow and Process Automation",
        category: "digital_transformation",
        points: 20,
        keywords: [
          "business process automation",
          "workflow automation project",
          "approval workflow automation",
          "back-office automation",
          "operations automation",
          "robotic process automation",
          "manual workflow replacement",
          "automated business processes",
          "power automate implementation",
          "automate dealer workflows",
          "automate cross-system",
        ],
      }),
      demand({
        id: "stellix_cloud_migration",
        label: "Cloud Migration or Cloud Modernization",
        category: "digital_transformation",
        points: 18,
        keywords: [
          "cloud migration project",
          "azure migration",
          "aws migration",
          "application cloud modernization",
          "migrate on-premise applications",
          "cloud-native modernization",
          "containerize legacy applications",
          "kubernetes migration",
          "infrastructure modernization",
        ],
      }),
      demand({
        id: "stellix_devops",
        label: "DevOps, CI/CD or Observability Initiative",
        category: "technology",
        points: 18,
        keywords: [
          "ci/cd implementation",
          "devops transformation",
          "deployment automation",
          "site reliability engineering",
          "observability implementation",
          "infrastructure as code",
          "docker adoption",
          "kubernetes implementation",
          "cloud monitoring",
          "distributed tracing",
          "application monitoring",
        ],
      }),
      demand({
        id: "stellix_ai",
        label: "AI, RAG or Intelligent Automation",
        category: "digital_transformation",
        points: 20,
        keywords: [
          "enterprise ai implementation",
          "generative ai application",
          "rag application",
          "retrieval augmented generation",
          "ai knowledge base",
          "ai workflow automation",
          "business ai assistant",
          "intelligent document processing",
          "ai integration project",
          "custom ai chatbot",
          "ai agent",
          "autonomous ai",
          "ai-driven",
          "ai applications",
          "deploying ai",
        ],
      }),
      demand({
        id: "stellix_salesforce",
        label: "Salesforce Development or Integration",
        category: "technology",
        points: 18,
        keywords: [
          "salesforce custom development",
          "salesforce integration",
          "apex development",
          "lightning web components",
          "salesforce process automation",
          "salesforce data migration",
          "salesforce org optimization",
          "salesforce external portal",
          "salesforce erp integration",
        ],
      }),
      demand({
        id: "stellix_healthcare",
        label: "Healthcare or MedTech Software Project",
        category: "technology",
        points: 20,
        keywords: [
          "ehr integration",
          "emr integration",
          "patient portal development",
          "clinician portal development",
          "medical registry platform",
          "healthcare software modernization",
          "telehealth platform",
          "hipaa compliant application",
          "medical device software platform",
          "healthcare data integration",
        ],
        industries: [
          "healthcare",
          "medtech",
          "medical devices",
          "pharmaceutical",
          "hospitals",
          "clinics",
          "health technology",
        ],
      }),
      demand({
        id: "stellix_manual_pain",
        label: "Manual Processes and Data Silos",
        category: "operational_pain",
        points: 15,
        keywords: [
          "spreadsheet-based process",
          "manual data entry",
          "manual reporting",
          "disconnected systems",
          "data silos",
          "duplicate data entry",
          "manual reconciliation",
          "email-based workflow",
          "fragmented software systems",
          "multiple disconnected applications",
          "manually rekeying",
          "manual rekeying",
          "rekeying data",
          "fragmented platforms",
          "fragmented platform",
        ],
      }),
      demand({
        id: "stellix_visibility_pain",
        label: "Real-Time Visibility or Reporting Pain",
        category: "operational_pain",
        points: 18,
        keywords: [
          "lack of real-time visibility",
          "delayed operational reporting",
          "inventory visibility problem",
          "shipment visibility problem",
          "real-time dashboard requirement",
          "operational dashboard initiative",
          "live tracking requirement",
          "delayed business data",
          "lack of centralized reporting",
        ],
      }),
      demand({
        id: "stellix_scalability_pain",
        label: "Performance, Reliability or Scalability Problems",
        category: "operational_pain",
        points: 18,
        keywords: [
          "application scalability problem",
          "system performance issues",
          "frequent application downtime",
          "deployment failures",
          "slow enterprise application",
          "reliability improvement program",
          "software performance bottleneck",
          "application stability problem",
          "unable to scale platform",
        ],
      }),
      supporting({
        id: "stellix_hiring",
        label: "Relevant Technical Hiring",
        category: "hiring",
        points: 10,
        keywords: [
          "hiring .net developer",
          "hiring cloud engineer",
          "hiring devops engineer",
          "hiring iot engineer",
          "hiring rfid engineer",
          "hiring full stack developers",
          "hiring software architect",
          "multiple software engineering openings",
          "engineering team expansion",
          "hiring software developers",
          "hiring software developer",
          "hiring for software developer",
          "scaling engineering",
          "scale engineering",
          "actively scaling their tech",
          "tech team is actively scaling",
          "experienced in bi and cloud",
        ],
        fieldKeys: ["hiringSignals", "triggerEvent", "recentNews", "notes"],
      }),
      supporting({
        id: "stellix_funding",
        label: "Funding, Acquisition or Private Equity Event",
        category: "funding",
        points: 6,
        keywords: [
          "series a funding",
          "series b funding",
          "growth equity investment",
          "private equity acquisition",
          "recently acquired",
          "merger integration",
          "post-acquisition technology integration",
          "investment for digital transformation",
          "strategic acquisition",
          "completed the acquisition",
          "completed acquisition",
          "took full ownership",
          "full ownership of",
        ],
        fieldKeys: ["recentNews", "triggerEvent", "notes"],
      }),
      supporting({
        id: "stellix_expansion",
        label: "New Facility or Operational Expansion",
        category: "expansion",
        points: 7,
        keywords: [
          "new warehouse opening",
          "new distribution center",
          "new manufacturing facility",
          "multi-location expansion",
          "operations expansion",
          "new site launch",
          "expanding warehouse network",
          "new production facility",
          "expanding the technology team",
          "technology team expansion",
          "expand technology team",
        ],
        industries: [
          "logistics",
          "warehousing",
          "manufacturing",
          "distribution",
          "supply chain",
          "retail",
          "healthcare",
        ],
        fieldKeys: ["recentNews", "triggerEvent", "hiringSignals", "notes"],
      }),
      demand({
        id: "stellix_compliance",
        label: "Compliance or Security Modernization",
        category: "compliance",
        points: 10,
        keywords: [
          "hipaa compliance project",
          "soc 2 readiness",
          "gdpr remediation",
          "audit trail requirement",
          "regulatory software upgrade",
          "cybersecurity remediation",
          "compliance modernization",
          "application security remediation",
          "data privacy modernization",
        ],
        industries: [
          "healthcare",
          "medtech",
          "pharmaceutical",
          "financial services",
          "insurance",
          "government",
          "enterprise software",
        ],
      }),
      supporting({
        id: "stellix_leadership",
        label: "New Technology or Transformation Leader",
        category: "custom",
        points: 7,
        keywords: [
          "appointed new cio",
          "appointed new cto",
          "new vp engineering",
          "new head of digital transformation",
          "new chief digital officer",
          "new vp technology",
          "new head of enterprise applications",
          "new technology transformation leader",
        ],
        fieldKeys: ["recentNews", "triggerEvent", "notes", "psLine"],
      }),
      demand({
        id: "stellix_website",
        label: "Website or Web Platform Rebuild",
        category: "website",
        points: 10,
        keywords: [
          "website redesign project",
          "website rebuild",
          "web application redesign",
          "customer experience portal",
          "ecommerce replatforming",
          "website performance improvement",
          "conversion optimization project",
          "outdated web platform",
          "digital customer experience modernization",
        ],
      }),
    ],
  };
}
